In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("raw_messy_dataset.csv")
data

Name      Age Gender              Email     Join_Date Salary  \
0      Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
1        Bob       40      M  user1@example.com           NaN  50000   
2    Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
3      David      NaN    NaN  user3@example.com    2021-05-21  70000   
4        Eva       35  Other  user4@example.com  July 4, 2020  70000   
..       ...      ...    ...                ...           ...    ...   
100    Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
101      Bob       40      M  user1@example.com           NaN  50000   
102  Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
103    David      NaN    NaN  user3@example.com    2021-05-21  70000   
104      Eva       35  Other  user4@example.com  July 4, 2020  70000   

      Department  
0          Admin  
1    Engineering  
2             HR  
3          Admin  
4    Engineering  
..           ...  
100        Admin  
101  Engineering  
102           HR  
103        Admin  
104  Engineering  

[105 rows x 7 columns]

In [75]:
data.head()
#data.tail()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        105 non-null    object
 1   Age         72 non-null     object
 2   Gender      89 non-null     object
 3   Email       95 non-null     object
 4   Join_Date   70 non-null     object
 5   Salary      78 non-null     object
 6   Department  89 non-null     object
dtypes: object(7)
memory usage: 5.9+ KB


In [76]:
#data.dropna(inplace=True)
print(data)
data.info()
data.describe()

        Name      Age Gender              Email     Join_Date Salary  \
0      Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
1        Bob       40      M  user1@example.com           NaN  50000   
2    Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
3      David      NaN    NaN  user3@example.com    2021-05-21  70000   
4        Eva       35  Other  user4@example.com  July 4, 2020  70000   
..       ...      ...    ...                ...           ...    ...   
100    Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
101      Bob       40      M  user1@example.com           NaN  50000   
102  Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
103    David      NaN    NaN  user3@example.com    2021-05-21  70000   
104      Eva       35  Other  user4@example.com  July 4, 2020  70000   

      Department  
0          Admin  
1    Engineering  
2             HR  
3          Admin  
4    Engineering  
..           ...  
10

Name Age Gender              Email   Join_Date Salary   Department
count     105  72     89                 95          70     78           89
unique     10   5      5                 90           4      5            5
top     Alice  40   Male  user0@example.com  2021-05-21  50000  Engineering
freq       11  22     22                  2          26     22           26

In [77]:
#duplicates removing
data.duplicated().sum()


np.int64(5)

In [78]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

np.int64(0)

In [79]:

data.columns

Index(['Name', 'Age', 'Gender', 'Email', 'Join_Date', 'Salary', 'Department'], dtype='object')

In [80]:
#handling age
data["Age"]=pd.to_numeric(data["Age"],errors='coerce')
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         57 non-null     float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [81]:
x=data["Age"].median()
data["Age"].fillna(x,inplace=True)
data["Age"].unique()

C:\Users\buras\AppData\Local\Temp\ipykernel_29488\3877753407.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(x,inplace=True)


array([35., 40., 30., 25.])

In [82]:
data["Gender"].unique()

array([nan, 'M', 'Male', 'Other', 'Female', 'F'], dtype=object)

In [83]:
#data["Gender"]=pd.replace({
 #   "M":"Male","F":"Female","":"None"
#})

In [84]:
data["Gender"]=data["Gender"].replace({
    "M":"Male","F":"Female","":"None"
})
data["Gender"].unique()

array([nan, 'Male', 'Other', 'Female'], dtype=object)

In [85]:
#Handling Emails
data["Email"].fillna("-",inplace=True)
print(data.to_string())

       Name   Age  Gender               Email     Join_Date   Salary   Department
0     Alice  35.0     NaN   user0@example.com    2021-05-21      NaN        Admin
1       Bob  40.0    Male   user1@example.com           NaN    50000  Engineering
2   Charlie  35.0    Male   user2@example.com    2020/01/01    50000           HR
3     David  35.0     NaN   user3@example.com    2021-05-21    70000        Admin
4       Eva  35.0   Other   user4@example.com  July 4, 2020    70000  Engineering
5     Frank  35.0   Other   user5@example.com           NaN    70000        Admin
6     Grace  35.0  Female   user6@example.com  July 4, 2020    80000  Engineering
7    Hannah  35.0   Other   user7@example.com    2021-05-21      NaN           HR
8       Ivy  30.0  Female   user8@example.com           NaN    50000  Engineering
9      Jack  35.0    Male   user9@example.com    2020/01/01    80000  Engineering
10    Alice  35.0    Male  user10@example.com    2021-05-21    70000  Engineering
11      Bob  35.

C:\Users\buras\AppData\Local\Temp\ipykernel_29488\2740383508.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Email"].fillna("-",inplace=True)


In [88]:

#data time change
data["Join_Data"]=pd.to_datatime(data["Join_Date"],errors="coerce")

AttributeError: module 'pandas' has no attribute 'to_datatime'

In [91]:
data["Salary"]=pd.to_numeric(data["Salary"],errors="coerce")
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       100 non-null    object 
 4   Join_Date   66 non-null     object 
 5   Salary      60 non-null     float64
 6   Department  84 non-null     object 
dtypes: float64(2), object(5)
memory usage: 6.2+ KB


In [98]:
y=data["Department"].mode()[0]
data["Department"].fillna(y,inplace=True)
data["Department"].unique()

array(['Admin', 'Engineering', 'HR', 'Sales', 'Marketing'], dtype=object)

In [99]:
data.to_csv("cleaned_csv")