In [9]:
num=int(input("Enter a num:"))
if num%2==0:
    print("Num is even")
else:
    print("num is odd")

Enter a num: 123


num is odd


In [3]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr.dtype)
print(arr.size)
print(arr.shape)

int64
10
(2, 5)


In [4]:
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,0])
newarr=np.concatenate((arr1,arr2))
print(newarr)


[1 2 3 4 5 6 7 8 9 0]


In [21]:
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,7)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8]), array([9])]


In [22]:
arr=np.array([1,3,2,4,5,6,4,3,2,4])
x=np.where(arr==4)
print(x)

(array([3, 6, 9]),)


In [24]:
arr=np.array([1,2,3,4,53,2,3,44,32])
newarr=np.sort(arr)
print(newarr)

print(np.sort(arr)[::-1])

[ 1  2  2  3  3  4 32 44 53]
[53 44 32  4  3  3  2  2  1]


In [29]:
#filtering
arr=np.array([32,44,21,4,56,54,88,67])
fil_arr=[]
for element in arr:
    if element>42:
        fil_arr.append(True)
    else:
        fil_arr.append(False)
newarr=np.array([fil_arr])
print(fil_arr)
print(newarr)

[False, True, False, False, True, True, True, True]
[[False  True False False  True  True  True  True]]


In [31]:
arr=np.array([23,44,32,23])
print(arr.astype(str))
print(arr.astype(float))

['23' '44' '32' '23']
[23. 44. 32. 23.]


In [38]:
arr=np.array([1,2,3,4,5])
print(np.append(arr,[50,60]))

print(np.insert(arr,3,100))

print(np.delete(arr,[2]))

[ 1  2  3  4  5 50 60]
[  1   2   3 100   4   5]
[1 2 4 5]


In [39]:
import statistics as stats
a=np.array([12,54,22,77,54,23,76,46,75])

print(np.min(a))

12
